# Use docker-based build environment (instead of openvz)
sudo: false
language: scala
scala:
- 2.11.6
jdk:
- openjdk8

cache:
  directories:
    - '$HOME/.ivy2/cache'

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
